// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/saveNewsletterSubscription.ts";
import * as $$$$$$$$$1 from "./actions/submitNewsletter.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$1 from "./sections/GoogleTagManager.tsx";
import * as $$$$$$2 from "./sections/ItWorks.tsx";
import * as $$$$$$3 from "./sections/LandingPage.tsx";
import * as $$$$$$4 from "./sections/PrimeiraConversaoLP.tsx";
import * as $$$$$$5 from "./sections/SimpleHeader.tsx";
import * as $$$$$$6 from "./sections/Theme/Favicon.tsx";
import * as $$$$$$7 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Footer.tsx": $$$$$$0,
    "site/sections/GoogleTagManager.tsx": $$$$$$1,
    "site/sections/ItWorks.tsx": $$$$$$2,
    "site/sections/LandingPage.tsx": $$$$$$3,
    "site/sections/PrimeiraConversaoLP.tsx": $$$$$$4,
    "site/sections/SimpleHeader.tsx": $$$$$$5,
    "site/sections/Theme/Favicon.tsx": $$$$$$6,
    "site/sections/Theme/Theme.tsx": $$$$$$7,
  },
  "actions": {
    "site/actions/saveNewsletterSubscription.ts": $$$$$$$$$0,
    "site/actions/submitNewsletter.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
